
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/kprashanth/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-41-generic - x86_64
...
